from server.services import ServiceError


def field_resolver(fields):
    res = []
    for k, v in fields.items():
        try:
            field_id = AC_FIELDS_MAP[k]
        except KeyError:
            raise ServiceError(f"Field {k} not found in ActiveCampaign fields mapping")
        res.append({"field": field_id, "value": v})
    return res


# curl -s --request GET --url 'https://themoderngroom.api-us1.com/api/3/fields?limit=1000' --header 'Api-Token: XXX' --header 'accept: application/json' | jq '.fields | map({(.perstag): .id}) | add' | pbcopy
AC_FIELDS_MAP = {
    "CUSTOMDEAL_VALUE": "68",
    "VENDOR_NAME": "108",
    "ROLE": "122",
    "NUMBER_IN_WEDDING_PARTY": "2",
    "PACKAGE": "69",
    "VENDOR_CODE": "109",
    "WEDDING_DATE": "3",
    "UTM_SOURCE": "5",
    "SUIT_1_COLOR": "70",
    "UTM_MEDIUM": "6",
    "PLANNED_WEDDING_DATE": "27",
    "SUIT_1_QUANTITY": "71",
    "CITY_STATE": "4",
    "UTM_CAMPAIGN": "7",
    "SUIT_2_COLOR": "72",
    "UTM_TERM": "8",
    "STATE": "38",
    "SUIT_2_QUANTITY": "73",
    "UTM_CONTENT": "9",
    "COMPANY_NAME": "10",
    "SUIT_3_COLOR": "98",
    "WEBSITE": "11",
    "LAST_CONTACT_SOURCE": "33",
    "SUIT_3_QUANTITY": "99",
    "PLEASE_SELECT_THE_PARTNERSHIP_OPTION_YOU_WOULD_PREFER": "12",
    "HOW_DID_YOU_HEAR_ABOUT_US": "55",
    "TIE_1_COLOR": "74",
    "DO_YOU_CURRENTLY_HAVE_PHOTOS_FEATURING_THE_MODERN_GROOMS_SUITS": "13",
    "TIE_1_QUANTITY": "75",
    "COUPON_CODE": "14",
    "TIE_2_COLOR": "76",
    "PARTNERSHIP_LINK": "15",
    "TIE_2_QUANTITY": "77",
    "MESSAGE": "16",
    "TIE_3_COLOR": "100",
    "STATEPROVINCE": "17",
    "TIE_3_QUANTITY": "101",
    "CONSULTANT": "18",
    "BOW_TIE_1_COLOR": "78",
    "TIME_UNTIL_WEDDING": "19",
    "BOW_TIE_1_QUANTITY": "79",
    "CONSULTSTYLE_SESSION_DETAILS": "21",
    "BOW_TIE_2_COLOR": "80",
    "CONSULT_DATE": "22",
    "BOW_TIE_2_QUANTITY": "81",
    "CONSULT_TIME": "23",
    "BOW_TIE_3_COLOR": "102",
    "ZOOM_LINK": "24",
    "CALENDLY_OWNER": "25",
    "BOW_TIE_3_QUANTITY": "103",
    "SHOE_1_COLOR": "82",
    "FIANCE_EMAIL": "26",
    "SHOE_1_QUANTITY": "83",
    "SUIT_COLOR": "28",
    "SHOE_2_COLOR": "84",
    "SHIRT_COLOR": "29",
    "SHOE_2_QUANTITY": "85",
    "TIE_COLOR": "30",
    "SOCK_1_QUANTITY": "87",
    "BRIDEGROOM": "31",
    "SOCK_2_QUANTITY": "89",
    "KIOSK_LOCATION": "32",
    "SOCK_1_COLOR": "90",
    "TIMEZONE": "34",
    "SOCK_2_COLOR": "91",
    "TMG_CONSULTANT": "35",
    "TRACKER_TIMESTAMP": "92",
    "CONSULT_DETAILS_FOR_TEXT_MESSAGE": "36",
    "WEDDING_PARTY_ORDER_LINK": "37",
    "LAST_MARKETING_START_DATE": "39",
    "DATE_THEY_BOOKED_CONSULT": "40",
    "WEDDING_PACKAGE_SELECTED_ON_DEAL": "54",
    "DATE_THEY_REGISTERED": "41",
    "LQ_REASON": "59",
    "ADDED_TO_NO_SHOW_DATE": "42",
    "TIME_UNTIL_CONSULT": "63",
    "ADDED_TO_ON_HOLD_DATE": "43",
    "CONSULT_RESCHEDULE_LINK": "64",
    "CANCELLED_CALL_DATE": "44",
    "CONSULT_CANCEL_LINK": "65",
    "FORM_COMPLETED_DATE": "45",
    "INBOUND_SMS_DETAILS": "66",
    "CALL_COMPLETED_DATE": "46",
    "WEEKS_TO_WEDDING": "67",
    "CANCELLED_WEDDING_DATE": "47",
    "WEDDING_LOCATION": "105",
    "DEAL_LOST_DATE": "48",
    "DAYS_UNTIL_ORDER_DATE": "107",
    "ADDED_TO_COMPLETED_EARLY_STAGES_DATE": "49",
    "WHAT_KIND_OF_EVENT_IS_THIS": "110",
    "NUMBER_OF_TOUCH_POINTS": "50",
    "ECOM_STATUS": "112",
    "NEW_LEAD_TO_BOOKED_TIMEFRAME": "51",
    "CONSULT_DATETIME_PRETTY": "116",
    "NEW_LEAD_TO_REGISTERED_TIMEFRAME": "52",
    "SHOPIFYACTIVATIONURL": "117",
    "BOOKED_TO_REGISTERED_TIMEFRAME": "53",
    "SHOPIFYCUSTOMERID": "118",
    "SHOPIFYEVENTURL": "119",
    "EVENT_DATE": "121",
    "NO_SHOWEDCANCELLED_CONVERSION_DATE": "56",
    "CONVERTED_OUT_OF_NOW_SHOWCANCELLED": "57",
    "CANCELLED_WEDDING_REASON": "58",
    "LQ_DATE": "60",
    "CONVERTED_BACK_FROM_LQ_DATE": "61",
    "CREATED_DATE": "62",
    "STAGE": "104",
    "ORDER_DATE": "106",
    "TRACKING_NUMBER": "114",
    "TRACKING_URL": "115",
    "GROOMS_NAME": "120",
}
