services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmg_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-api:
    image: python:3.12
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tmg_api
      DB_USER: postgres
      DB_PASSWORD: postgres
    working_dir: /usr/src/app/
    command: >
      bash -c "pip install tox &&
      git config --global --add safe.directory /usr/src/app &&
      tox &&
      . .tox/py312/bin/activate && 
      pip install --upgrade psycopg2 &&
      ./scripts/reset_db.sh &&
      cd server/ &&
      pytest --verbose"
    depends_on:
      - db

  test-end-to-end:
    image: mcr.microsoft.com/playwright/python:v1.43.0-jammy
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/tests
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "pip install pytest pytest-playwright &&
      pytest --verbose"
    tty: false
    restart: "no"

volumes:
  postgres_data:
