version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmg_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: python:3.10
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "apt-get update && apt-get install -y git && pip install tox && tox && . .tox/py3/bin/activate && pytest --verbose"
    depends_on:
      - db

volumes:
  postgres_data:
