services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmg_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-api:
    image: python:3.12
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tmg_api
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_POOL_SIZE: 100
    working_dir: /usr/src/app/
    command: >
      bash -c "pip install tox &&
      git config --global --add safe.directory /usr/src/app &&
      tox &&
      . .tox/py312/bin/activate && 
      pip install --upgrade psycopg2 &&
      ./scripts/reset_db.sh &&
      cd server/ &&
      pytest --verbose"
    depends_on:
      - db

  app:
    image: python:3.12
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tmg_api
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_POOL_SIZE: 100
      TMG_APP_TESTING: 'true'
    working_dir: /usr/src/app/
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r requirements.txt &&
      pip install --upgrade psycopg2 &&
      ./scripts/reset_db.sh &&
      python main.py"
    depends_on:
      - db

  smoke-test:
    image: python:3.12
    command: >
      bash -c "
      echo 'Waiting for up to 45 sec for app to start ...' &&
      timeout 45 bash -c 'while ! curl -s -o /dev/null -w '%{http_code}' http://app:8080/health | grep -q 200; do
        sleep 1;
      done'"
    depends_on:
      - db
      - app

  test-end-to-end:
    image: mcr.microsoft.com/playwright/python:v1.43.0-jammy
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/tests
    environment:
      PYTHONUNBUFFERED: 1
      ACTIVE_ENV: ${ACTIVE_ENV:-stg}
      BROWSER: ${BROWSER:-chromium}
    command: >
      bash -c "pip install pytest pytest-playwright &&
      pytest --verbose --browser $BROWSER"
    tty: false
    restart: "no"

volumes:
  postgres_data:
