service: tmg-api
provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-west-2
  profile: tmg-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
resources:
  Resources:
    MyLambdaFunctionProvisionedConcurrency:
      Type: AWS::Lambda::ProvisionedConcurrencyConfig
      Properties:
        FunctionName:
          Fn::GetAtt:
            - HelloLambdaFunction
            - Arn
        ProvisionedConcurrentExecutions: 10  # Adjust the concurrency as needed
plugins:
  - serverless-python-requirements
