service: tmg-api
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  profile: ${self:custom.${self:provider.stage}.profile, 'tmg-dev'}
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  provisionedConcurrency: 1

plugins:
  - serverless-python-requirements

stages:
  - dev
  - steve

# custom:
#   # Define environment variables for different stages
#   dev:
#   steve:
