service: tmg-api
provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: us-west-2
  iam:
    role:
      name: tmg-api-${sls:stage}-role
  logs:
    restApi:
      accessLogging: true
      format: '$context.requestTime "$context.httpMethod $context.path $context.protocol" $context.status $context.identity.sourceIp $context.requestId'

functions:
  api:
    handler: main.lambda_handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    provisionedConcurrency: 1
    reservedConcurrency: 10
    timeout: 3
    vpc:
      securityGroupIds:
        - sg-0649f5114f8fdde15
      subnetIds:
        - subnet-0558d5c84f76f6246
        - subnet-081fa5d80ecd9a253
    environment:
      # SQLAlchemy Env Variables
      DB_HOST: tmg-api-db-01.cfbqizbq9cdk.us-west-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: tmg_api
      DB_USER: postgres
      DB_PASSWORD: ${ssm:/db/tmg-api-db/DB_PASSWORD}
      # Shopify Env Variables
      API_KEY: ${ssm:/shopify/c2/API_KEY}
      sender_email: "bsit833@gmail.com"
      sender_password: ${ssm:/shopify/c2/sender_password}
      api_version: "2024-01"
      shopify_store: "themodern-groom"
      client_id: ${ssm:/shopify/c2/client_id}
      client_secret: ${ssm:/shopify/c2/client_secret}
      SECRET_KEY_C2: ${ssm:/shopify/c2/client_secret}
      admin_api_access_token: ${ssm:/shopify/c2/admin_api_access_token}

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-plugin-datadog

custom:
  # https://github.com/amplify-education/serverless-domain-manager/tree/main 
  customDomain:
    domainName: "api.dev.tmgcorp.net"
    basePath: ''
    certificateName: '*.dev.tmgcorp.net'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false

  # https://docs.datadoghq.com/serverless/libraries_integrations/plugin/
  datadog:
    enabled: false
    site: us5.datadoghq.com
    apiKey: ${ssm:/sls/datadog/api_key}
    appKey: ${ssm:/sls/datadog/app_key}
    enableDDLogs: false
    enableXrayTracing: false
    enableDDTracing: false
    # enableASM: false
    enableProfiling: false
    enableSourceCodeIntegration: false
    enableColdStartTracing: false
    uploadGitMetadata: false
    addLayers: false
    addExtension: false
    encodeAuthorizerContext: false
    decodeAuthorizerContext: false
    subscribeToAccessLogs: true
    subscribeToExecutionLogs: true
    forwarderArn: arn:aws:lambda:us-west-2:828867313984:function:DatadogIntegration-ForwarderStack-AS2SOT-Forwarder-GHUaejGvjpIq
    failOnError: true
    logLevel: DEBUG
    service: tmg-api
    env: dev
    subdomain: "api.dev.tmgcorp.net"
    # https://docs.datadoghq.com/serverless/libraries_integrations/plugin/#serverless-monitors
    monitors:
      - high_error_rate:
          name: "High Error Rate on {{functionname}}"
          message: "More than 10% of the function's invocations are errors. Notify @slack-notifications"
          options:
            include_tags: false
      - timeout:
          name: "Timeout on {{functionname}}"
          message: "The function has timed out. Notify @slack-notifications"
          options:
            include_tags: false
      - high_throttles:
          name: "High Throttles on {{functionname}}"
          message: "More than 20% of the function's invocations are throttled. Notify @slack-notifications"
          options:
            include_tags: false

package:
  exclude:
    - .serverless/**
    - .tox/**
    - .build/**
    - .git/**
    - '.vscode/**'
    - node_modules/**
    - venv/**
    - doc/**
    - "__pycache__/**"
    - "**/__pycache__/**"
    - ".#*"