"""RMA type remove

Revision ID: 104060d3bee0
Revises: 9283fa414acd
Create Date: 2024-03-18 20:40:57.446569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "104060d3bee0"
down_revision: Union[str, None] = "9283fa414acd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rma_items", ["id"])
    op.create_unique_constraint(None, "rmas", ["id"])
    op.drop_column("rmas", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rmas",
        sa.Column(
            "type",
            postgresql.ENUM("RESIZE", "DAMAGED", "CANCELLATION", "EXCHANGE", name="rmatype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "rmas", type_="unique")
    op.drop_constraint(None, "rma_items", type_="unique")
    # ### end Alembic commands ###
