"""Added product_items table

Revision ID: 1165f59dc4f7
Revises: d4553f441397
Create Date: 2024-04-25 22:11:07.641661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1165f59dc4f7"
down_revision: Union[str, None] = "d4553f441397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("sku", sa.String(), nullable=True),
        sa.Column("weight_lb", sa.Float(), nullable=True),
        sa.Column("height_in", sa.Float(), nullable=True),
        sa.Column("width_in", sa.Float(), nullable=True),
        sa.Column("length_in", sa.Float(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("on_hand", sa.Integer(), nullable=True),
        sa.Column("allocated", sa.Integer(), nullable=True),
        sa.Column("reserve", sa.Integer(), nullable=True),
        sa.Column("non_sellable_total", sa.Integer(), nullable=True),
        sa.Column("reorder_level", sa.Integer(), nullable=True),
        sa.Column("reorder_amount", sa.Integer(), nullable=True),
        sa.Column("replenishment_level", sa.Integer(), nullable=True),
        sa.Column("available", sa.Integer(), nullable=True),
        sa.Column("backorder", sa.Integer(), nullable=True),
        sa.Column("barcode", sa.Numeric(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.VARCHAR()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_items_is_active"), "product_items", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_items_is_active"), table_name="product_items")
    op.drop_table("product_items")
    # ### end Alembic commands ###
