"""Added orders table

Revision ID: 1f5be499a629
Revises: 315a25851f5f
Create Date: 2024-04-25 21:56:51.999730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f5be499a629"
down_revision: Union[str, None] = "315a25851f5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "attendees", ["id"])
    op.add_column("orders", sa.Column("event_id", sa.UUID(), nullable=True))
    op.add_column("orders", sa.Column("received_date", sa.DateTime(), nullable=True))
    op.create_foreign_key(None, "orders", "events", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "received_date")
    op.drop_column("orders", "event_id")
    op.drop_constraint(None, "attendees", type_="unique")
    # ### end Alembic commands ###
