"""Dateless events

Revision ID: 48360ab6ecae
Revises: 01ebc7f29ca9
Create Date: 2024-10-22 14:21:30.870231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48360ab6ecae"
down_revision: Union[str, None] = "01ebc7f29ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "event_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("events", "event_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###
