"""rename cols

Revision ID: 4ed280b49c44
Revises: 9577d0b2d7d8
Create Date: 2024-05-07 20:17:16.806047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ed280b49c44"
down_revision: Union[str, None] = "9577d0b2d7d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rma_items", "type2", nullable=False, new_column_name="type")
    op.alter_column("rma_items", "reason2", nullable=False, new_column_name="reason")
    op.alter_column("rmas", "status2", nullable=False, new_column_name="status")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
