"""Added order_items table

Revision ID: 5718d6e61f1d
Revises: 1f5be499a629
Create Date: 2024-04-25 22:02:37.056732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5718d6e61f1d"
down_revision: Union[str, None] = "1f5be499a629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_items", sa.Column("price", sa.Float(), nullable=True))
    op.alter_column("order_items", "order_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order_items", "order_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("order_items", "price")
    # ### end Alembic commands ###
