"""Added diff column to audit log

Revision ID: 59d0bb205ba5
Revises: 08387d1c14a3
Create Date: 2024-10-18 12:31:07.943876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59d0bb205ba5"
down_revision: Union[str, None] = "08387d1c14a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_logs", "diff")
    # ### end Alembic commands ###
