"""Anon checkout updates

Revision ID: 67b58bce2d7e
Revises: 82dd141f5171
Create Date: 2024-11-15 10:46:27.641952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67b58bce2d7e"
down_revision: Union[str, None] = "82dd141f5171"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("measurements", sa.Column("email", sa.String(), nullable=True))
    op.alter_column("measurements", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_index("ix_shopify_products_product_id", table_name="shopify_products")
    op.drop_index("ix_shopify_products_variants_id", table_name="shopify_products", postgresql_using="gin")
    op.drop_index("ix_shopify_products_variants_sku", table_name="shopify_products", postgresql_using="gin")
    op.add_column("sizes", sa.Column("email", sa.String(), nullable=True))
    op.alter_column("sizes", "user_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("users", sa.Column("sms_consent", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("email_consent", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_consent")
    op.drop_column("users", "sms_consent")
    op.alter_column("sizes", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("sizes", "email")
    op.create_index(
        "ix_shopify_products_variants_sku",
        "shopify_products",
        [sa.text('jsonb_path_query_array(data, \'$."variants"[*]."sku"\'::jsonpath)')],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_shopify_products_variants_id",
        "shopify_products",
        [sa.text('jsonb_path_query_array(data, \'$."variants"[*]."id"\'::jsonpath)')],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_shopify_products_product_id", "shopify_products", ["product_id"], unique=True)
    op.alter_column("measurements", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("measurements", "email")
    # ### end Alembic commands ###
