"""Anon looks

Revision ID: 69b18ed8c772
Revises: 67b58bce2d7e
Create Date: 2024-11-15 12:44:56.545357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69b18ed8c772"
down_revision: Union[str, None] = "67b58bce2d7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("looks", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("looks", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
