"""Added looks table

Revision ID: 6ac5fb206d56
Revises: f9f4a6a1d958
Create Date: 2024-04-25 21:48:02.035034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ac5fb206d56"
down_revision: Union[str, None] = "f9f4a6a1d958"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "looks",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("look_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("product_specs", sa.JSON(), nullable=True),
        sa.Column("product_final_image", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_looks_look_name"), "looks", ["look_name"], unique=False)
    op.create_unique_constraint(None, "events", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="unique")
    op.drop_index(op.f("ix_looks_look_name"), table_name="looks")
    op.drop_table("looks")
    # ### end Alembic commands ###
