"""update rmas

Revision ID: 81fce49af6f4
Revises: f24b8b64bcd3
Create Date: 2024-05-07 17:35:44.227033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81fce49af6f4"
down_revision: Union[str, None] = "f24b8b64bcd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    rmaitemtype2 = sa.Enum("REFUND", "EXCHANGE", name="rmaitemtype2")
    rmaitemtype2.create(op.get_bind())
    rmaitemreason = sa.Enum("DISLIKED", "TOO_BIG", "TOO_SMALL", "DAMAGED", "WRONG_ITEM", name="rmaitemreason")
    rmaitemreason.create(op.get_bind())
    rmastatus2 = sa.Enum("PENDING", "PENDING_CS_ACTION", "WAREHOUSE_COMPLETE", "COMPLETED", name="rmastatus2")
    rmastatus2.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rma_items", sa.Column("quantity_received", sa.Integer(), nullable=True))
    op.add_column("rma_items", sa.Column("type2", rmaitemtype2, nullable=True))
    op.add_column("rma_items", sa.Column("reason2", rmaitemreason, nullable=True))
    op.add_column("rmas", sa.Column("status2", rmastatus2, nullable=True))
    op.add_column("rmas", sa.Column("refund_amount", sa.Numeric(), nullable=True))
    op.add_column("rmas", sa.Column("shiphero_id", sa.String(), nullable=True))
    op.add_column("rmas", sa.Column("warehouse_notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rmas", "warehouse_notes")
    op.drop_column("rmas", "shiphero_id")
    op.drop_column("rmas", "refund_amount")
    op.drop_column("rmas", "status2")
    op.drop_column("rma_items", "reason2")
    op.drop_column("rma_items", "type2")
    op.drop_column("rma_items", "quantity_received")
    # ### end Alembic commands ###
