"""Add measurement_id to sizes

Revision ID: 866573db5e09
Revises: 369102a36dec
Create Date: 2024-08-07 15:39:33.161124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "866573db5e09"
down_revision: Union[str, None] = "369102a36dec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sizes", sa.Column("measurement_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "sizes", "measurements", ["measurement_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sizes", type_="foreignkey")
    op.drop_column("sizes", "measurement_id")
    # ### end Alembic commands ###
