"""remove variant_id and product_id from suit_builder

Revision ID: 882ea810a4d3
Revises: 48360ab6ecae
Create Date: 2024-10-30 16:01:21.090366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "882ea810a4d3"
down_revision: Union[str, None] = "48360ab6ecae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("suit_builder_items", "variant_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("suit_builder_items", "product_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("suit_builder_items", "product_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("suit_builder_items", "variant_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
