"""added firstname, lastname, email to attendees table

Revision ID: 88351716a120
Revises: 1db093b780f6
Create Date: 2024-09-24 18:11:14.168819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88351716a120"
down_revision: Union[str, None] = "1db093b780f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attendees", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("attendees", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("attendees", sa.Column("email", sa.String(), nullable=True))
    op.alter_column("attendees", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attendees", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("attendees", "email")
    op.drop_column("attendees", "last_name")
    op.drop_column("attendees", "first_name")
    # ### end Alembic commands ###
