"""Enriched users table

Revision ID: 94135d5b02ad
Revises: c0fd58aba81c
Create Date: 2024-04-25 21:05:42.211997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94135d5b02ad"
down_revision: Union[str, None] = "c0fd58aba81c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("shopify_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("account_status", sa.Boolean(), nullable=True))
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "users", ["shopify_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "account_status")
    op.drop_column("users", "shopify_id")
    # ### end Alembic commands ###
