"""remove variant_id and product_id from suit_builder

Revision ID: bc93acc826a0
Revises: 48360ab6ecae
Create Date: 2024-10-30 17:42:10.958501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc93acc826a0"
down_revision: Union[str, None] = "48360ab6ecae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suit_builder_items", "product_id")
    op.drop_column("suit_builder_items", "variant_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("suit_builder_items", sa.Column("variant_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column("suit_builder_items", sa.Column("product_id", sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
