"""Added new discount type

Revision ID: be9321b3db34
Revises: 08387d1c14a3
Create Date: 2024-10-03 16:26:43.881394

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be9321b3db34"
down_revision: Union[str, None] = "08387d1c14a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE discounttype ADD VALUE 'CUSTOM'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
