"""Added roles table

Revision ID: d027fd786af1
Revises: 6ac5fb206d56
Create Date: 2024-04-25 21:49:58.763672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d027fd786af1"
down_revision: Union[str, None] = "6ac5fb206d56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("role_name", sa.String(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("look_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["look_id"],
            ["looks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_roles_role_name"), "roles", ["role_name"], unique=False)
    op.create_unique_constraint(None, "looks", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "looks", type_="unique")
    op.drop_index(op.f("ix_roles_role_name"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
