from server.services import ServiceError


def field_resolver(fields):
    res = []
    for k, v in fields.items():
        try:
            field_id = AC_FIELDS_MAP[k]
        except KeyError:
            raise ServiceError(f"Field {k} not found in ActiveCampaign fields mapping")
        res.append({"field": field_id, "value": v})
    return res


# curl --request GET --url 'https://themoderngroom.api-us1.com/api/3/fields' --header 'Api-Token: XXX' --header 'accept: application/json' | jq .fields | pbcopy
AC_FIELDS = [
    {
        "title": "Number in Wedding Party",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "NUMBER_IN_WEDDING_PARTY",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "0",
        "cdate": "2020-03-27T14:05:11-05:00",
        "udate": "2022-05-03T14:41:31-05:00",
        "created_timestamp": "2020-03-27 14:05:11",
        "updated_timestamp": "2020-03-27 14:05:11",
        "created_by": "0",
        "updated_by": "1",
        "options": [],
        "relations": ["2"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/2/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/2/relations",
        },
        "id": "2",
    },
    {
        "title": "Deal Value",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "CUSTOMDEAL_VALUE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "0",
        "cdate": "2023-08-14T10:06:24-05:00",
        "udate": "2023-08-28T07:42:09-05:00",
        "created_timestamp": "2023-08-14 10:06:24",
        "updated_timestamp": "2023-08-14 10:06:24",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["116"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/68/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/68/relations",
        },
        "id": "68",
    },
    {
        "title": "Vendor Name",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "VENDOR_NAME",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "0",
        "cdate": "2023-11-20T11:12:05-06:00",
        "udate": "2023-11-20T11:12:32-06:00",
        "created_timestamp": "2023-11-20 11:12:05",
        "updated_timestamp": "2023-11-20 11:12:05",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["163"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/108/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/108/relations",
        },
        "id": "108",
    },
    {
        "title": "Wedding Date",
        "descript": "",
        "type": "date",
        "isrequired": "0",
        "perstag": "WEDDING_DATE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "1",
        "cdate": "2020-03-27T14:05:33-05:00",
        "udate": "2022-05-03T14:41:31-05:00",
        "created_timestamp": "2020-03-27 14:05:33",
        "updated_timestamp": "2020-03-27 14:05:33",
        "created_by": "0",
        "updated_by": "1",
        "options": [],
        "relations": ["3"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/3/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/3/relations",
        },
        "id": "3",
    },
    {
        "title": "Package",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "PACKAGE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "1",
        "cdate": "2023-08-14T10:06:49-05:00",
        "udate": "2023-08-28T07:42:09-05:00",
        "created_timestamp": "2023-08-14 10:06:50",
        "updated_timestamp": "2023-08-14 10:06:50",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["117"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/69/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/69/relations",
        },
        "id": "69",
    },
    {
        "title": "Vendor Code",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "VENDOR_CODE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "1",
        "cdate": "2023-11-20T11:12:22-06:00",
        "udate": "2023-11-20T11:12:32-06:00",
        "created_timestamp": "2023-11-20 11:12:22",
        "updated_timestamp": "2023-11-20 11:12:22",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["164"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/109/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/109/relations",
        },
        "id": "109",
    },
    {
        "title": "utm_source",
        "descript": "",
        "type": "hidden",
        "isrequired": "0",
        "perstag": "UTM_SOURCE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "2",
        "cdate": "2020-10-05T16:02:30-05:00",
        "udate": "2023-11-20T11:12:32-06:00",
        "created_timestamp": "2020-10-05 16:02:30",
        "updated_timestamp": "2020-10-05 16:02:30",
        "created_by": "0",
        "updated_by": "44",
        "options": [],
        "relations": ["29"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/5/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/5/relations",
        },
        "id": "5",
    },
    {
        "title": "Planned Wedding Date",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "PLANNED_WEDDING_DATE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "2",
        "cdate": "2021-06-14T11:04:26-05:00",
        "udate": "2022-05-03T14:41:31-05:00",
        "created_timestamp": "2021-06-14 11:04:26",
        "updated_timestamp": "2021-06-14 11:04:26",
        "created_by": "2",
        "updated_by": "1",
        "options": [],
        "relations": ["45"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/27/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/27/relations",
        },
        "id": "27",
    },
    {
        "title": "Suit 1 Color",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "SUIT_1_COLOR",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "2",
        "cdate": "2023-08-14T10:07:04-05:00",
        "udate": "2023-08-28T07:42:09-05:00",
        "created_timestamp": "2023-08-14 10:07:04",
        "updated_timestamp": "2023-08-14 10:07:04",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["118"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/70/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/70/relations",
        },
        "id": "70",
    },
    {
        "title": "City, State",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "CITY_STATE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "3",
        "cdate": "2020-03-27T14:41:43-05:00",
        "udate": "2022-05-03T14:41:31-05:00",
        "created_timestamp": "2020-03-27 14:41:43",
        "updated_timestamp": "2020-03-27 14:41:43",
        "created_by": "0",
        "updated_by": "1",
        "options": [],
        "relations": ["4"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/4/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/4/relations",
        },
        "id": "4",
    },
    {
        "title": "utm_medium",
        "descript": "",
        "type": "hidden",
        "isrequired": "0",
        "perstag": "UTM_MEDIUM",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "3",
        "cdate": "2020-10-05T16:03:02-05:00",
        "udate": "2023-11-20T11:12:32-06:00",
        "created_timestamp": "2020-10-05 16:03:02",
        "updated_timestamp": "2020-10-05 16:03:02",
        "created_by": "0",
        "updated_by": "44",
        "options": [],
        "relations": ["30"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/6/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/6/relations",
        },
        "id": "6",
    },
    {
        "title": "Suit 1 Quantity ",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "SUIT_1_QUANTITY",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "3",
        "cdate": "2023-08-14T10:07:19-05:00",
        "udate": "2023-08-28T07:42:09-05:00",
        "created_timestamp": "2023-08-14 10:07:19",
        "updated_timestamp": "2023-08-14 10:07:19",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["119"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/71/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/71/relations",
        },
        "id": "71",
    },
    {
        "title": "utm_campaign",
        "descript": "",
        "type": "hidden",
        "isrequired": "0",
        "perstag": "UTM_CAMPAIGN",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "4",
        "cdate": "2020-10-05T16:03:11-05:00",
        "udate": "2023-11-20T11:12:31-06:00",
        "created_timestamp": "2020-10-05 16:03:11",
        "updated_timestamp": "2020-10-05 16:03:11",
        "created_by": "0",
        "updated_by": "44",
        "options": [],
        "relations": ["31"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/7/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/7/relations",
        },
        "id": "7",
    },
    {
        "title": "State Dropdown",
        "descript": "",
        "type": "dropdown",
        "isrequired": "0",
        "perstag": "STATE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "4",
        "cdate": "2022-05-03T14:41:14-05:00",
        "udate": "2022-05-03T14:41:49-05:00",
        "created_timestamp": "2022-05-03 14:41:14",
        "updated_timestamp": "2022-05-03 14:41:14",
        "created_by": "1",
        "updated_by": "1",
        "options": [
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
            "61",
        ],
        "relations": ["57"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/38/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/38/relations",
        },
        "id": "38",
    },
    {
        "title": "Suit 2 Color",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "SUIT_2_COLOR",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "4",
        "cdate": "2023-08-14T10:07:28-05:00",
        "udate": "2023-08-28T07:42:09-05:00",
        "created_timestamp": "2023-08-14 10:07:28",
        "updated_timestamp": "2023-08-14 10:07:28",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["120"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/72/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/72/relations",
        },
        "id": "72",
    },
    {
        "title": "utm_term",
        "descript": "",
        "type": "hidden",
        "isrequired": "0",
        "perstag": "UTM_TERM",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "5",
        "cdate": "2020-10-05T16:03:17-05:00",
        "udate": "2023-11-20T11:12:32-06:00",
        "created_timestamp": "2020-10-05 16:03:17",
        "updated_timestamp": "2020-10-05 16:03:17",
        "created_by": "0",
        "updated_by": "44",
        "options": [],
        "relations": ["32"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/8/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/8/relations",
        },
        "id": "8",
    },
    {
        "title": "Company Name",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "COMPANY_NAME",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "5",
        "cdate": "2020-11-10T01:40:12-06:00",
        "udate": "2022-05-03T14:41:31-05:00",
        "created_timestamp": "2020-11-10 01:40:12",
        "updated_timestamp": "2020-11-10 01:40:12",
        "created_by": "2",
        "updated_by": "1",
        "options": [],
        "relations": ["20"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/10/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/10/relations",
        },
        "id": "10",
    },
    {
        "title": "Suit 2 Quantity",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "SUIT_2_QUANTITY",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "5",
        "cdate": "2023-08-14T10:07:43-05:00",
        "udate": "2023-08-28T07:42:09-05:00",
        "created_timestamp": "2023-08-14 10:07:43",
        "updated_timestamp": "2023-08-14 10:07:43",
        "created_by": "44",
        "updated_by": "44",
        "options": [],
        "relations": ["121"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/73/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/73/relations",
        },
        "id": "73",
    },
    {
        "title": "utm_content",
        "descript": "",
        "type": "hidden",
        "isrequired": "0",
        "perstag": "UTM_CONTENT",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "6",
        "cdate": "2020-10-05T16:03:25-05:00",
        "udate": "2023-11-20T11:12:31-06:00",
        "created_timestamp": "2020-10-05 16:03:25",
        "updated_timestamp": "2020-10-05 16:03:25",
        "created_by": "0",
        "updated_by": "44",
        "options": [],
        "relations": ["33"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/9/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/9/relations",
        },
        "id": "9",
    },
    {
        "title": "Website",
        "descript": "",
        "type": "text",
        "isrequired": "0",
        "perstag": "WEBSITE",
        "defval": "",
        "show_in_list": "0",
        "rows": "0",
        "cols": "0",
        "visible": "1",
        "service": "",
        "ordernum": "6",
        "cdate": "2020-11-10T01:40:48-06:00",
        "udate": "2022-05-03T14:41:31-05:00",
        "created_timestamp": "2020-11-10 01:40:48",
        "updated_timestamp": "2020-11-10 01:40:48",
        "created_by": "2",
        "updated_by": "1",
        "options": [],
        "relations": ["21"],
        "links": {
            "options": "https://themoderngroom.api-us1.com/api/3/fields/11/options",
            "relations": "https://themoderngroom.api-us1.com/api/3/fields/11/relations",
        },
        "id": "11",
    },
]

AC_FIELDS_MAP = {f["perstag"]: f["id"] for f in AC_FIELDS}
