name: _e2e_clean_up

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
        description: Stage to run clean up against

jobs:
  e2e-clean-up-shopify-and-db:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - name: Clean up e2e test data from Shopify and DB
        run: |
          curl https://api.${{ inputs.stage }}.tmgcorp.net/jobs/system/e2e-clean-up \
            -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-ACCESS-TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}" \
            -d '{}' \
            --max-time 300

  e2e-clean-up-active-campaign:
    runs-on: ubuntu-latest
    if: ${{ inputs.stage == 'prd' }}
    environment: ${{ inputs.stage }}
    steps:
      - name: Clean up e2e test data from Active Campaign
        run: |
          curl https://api.${{ inputs.stage }}.tmgcorp.net/jobs/system/e2e-ac-clean-up \
            -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-ACCESS-TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}" \
            -d '{}' \
            --max-time 300
