name: cd

on:
  workflow_dispatch: {}
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Setup Node.js 21.x
        uses: actions/setup-node@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::828867313984:role/SlsDeploy
          
      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: init deploy

