name: cd

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency:
  group: cd
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  sls-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
        
      - name: Install Serverless
        run: npm install -g serverless@3.38.*

      - name: Install Serverless dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::828867313984:role/SlsDeploy

      - name: Sls Deploy
        run: sls deploy --stage dev
      
      - name: Notify Slack
        if: ${{ always() }}
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: 'C06KT69EN30' # Notifications
          slack-message: |
            Serverless Deployment ${{ job.status == 'success' && 'Completed :rocket:' || 'Failed :hot_face:' }}
            Repo: ${{ github.repository }}
            Ref: ${{ github.ref }}
            Job Status: ${{ job.status }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
        
