name: Docker

on:
  push:
    - dev


jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: alitmg/tmg-apis:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: NicksMenswear/tmg-api/ssh-action@dev
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop tmg-apis || true
            docker rm tmg-apis || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/tmg-apis:${{ github.sha }}
            docker run -d --name tmg-apis -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/tmg-apis:${{ github.sha }}
