name: on-release

on:
  workflow_dispatch:
    inputs:
      stage:
        type: string
        description: semver
        required: true

jobs:
  ci:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      ref: ${{ github.ref_name }}

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    with:
      ref: ${{ github.ref_name }}
      stage: stg
  
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: ${{ github.ref_name }}
      stage: stg