name: END-TO-END-TESTS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,12,14,16,18,20,22 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Set up Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#
#      - name: Build and run end-to-end tests
#        run: ./test-end-to-end.sh
#
#      - name: Clean up
#        if: always()
#        run: docker-compose down
#
      - name: Notify to Slack
#        if: failure()
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'C06V758NKQF'
          slack-message: 'E2E tests failed :warning:'
