name: on-merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - 'scripts/**'
      - 'README.md'
      - 'test-*'

concurrency:
  group: ${{ github.workflow.name }}
  cancel-in-progress: false

jobs:
  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
  
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true