name: on-merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'scripts/**'
      - 'README.md'
      - 'test-*'
      - '.github/**'

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      ref: ${{ github.sha }}

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    needs: ci
    with:
      ref: ${{ github.sha }}
      stage: dev
      url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-tests:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
      SHOPIFY_ADMIN_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_ACCESS_TOKEN }}