name: on-merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - 'scripts/**'
      - 'README.md'
      - 'test-*'

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      ref: ${{ github.sha }}  

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    needs: ci
    with:
      ref: ${{ github.sha }}
      stage: dev
      url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  
  e2e-group-1:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
      test_group: group-1
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-group-2:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
      test_group: group-2
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-group-3:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
      test_group: group-3
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-group-4:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
      test_group: group-4
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-group-5:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
      test_group: group-5
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}