name: on-merge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - 'scripts/**'
      - 'README.md'
      - 'test-*'

concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      ref: ${{ github.sha }}  

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    needs: ci
    with:
      ref: ${{ github.sha }}
      stage: dev
      url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  
  e2e-tests:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    strategy:
      matrix:
        group_number: [1, 2, 3, 4, 5]
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
      test_group: group-${{ matrix.group_number }}
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-clean-up:
    uses: ./.github/workflows/_e2e_clean_up.yml
    needs:
      - e2e-tests
    if: ${{ always() }}
    with:
      stage: dev
    environment: dev
    secrets:
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}