name: on-pull-request-comment

on:
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-dev
  cancel-in-progress: false

permissions: 
  id-token: write
  contents: write
  pull-requests: write
  statuses: write
  checks: read

jobs:
  report-start:
    if: ${{ github.event.issue.pull_request != '' && contains(github.event.comment.body, '/e2e') }}
    runs-on: ubuntu-latest
    steps:
      - name: Update PR status
        uses: teamniteo/pull_request_status_action@v1.0.0
        with:
          pr_number: ${{ github.event.issue.number }}
          state: pending
          repository: ${{ github.repository }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          context: "on-pull-request-comment / e2e"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  await-ci:
    if: ${{ github.event.issue.pull_request != '' && contains(github.event.comment.body, '/e2e') }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI gate status
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-gate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.sha }}
          checkName: "ci / gate"
      
      - name: Assert CI gate status
        run: ${{ steps.wait-for-gate.outputs.conclusion == 'success' }}

  cd:
    if: ${{ github.event.issue.pull_request != '' && contains(github.event.comment.body, '/e2e') }}
    uses: ./.github/workflows/_sls_deploy.yml
    needs: await-ci
    with:
      ref: ${{ github.sha }}
      stage: dev
      notify: false
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
  
  e2e:
    if: ${{ github.event.issue.pull_request != '' && contains(github.event.comment.body, '/e2e') }}
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.sha }}
      stage: dev
      notify: false
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

  report-finish:
    if: ${{ always() && github.event.issue.pull_request != '' && contains(github.event.comment.body, '/e2e') }}
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Update PR status
        uses: teamniteo/pull_request_status_action@v1.0.0
        with:
          pr_number: ${{ github.event.issue.number }}
          state: ${{ needs.e2e.result == 'success' && 'success' || 'failure'}}
          repository: ${{ github.repository }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          context: "on-pull-request-comment / e2e"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


