name: on-pull-request

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled

jobs:
  ci:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      ref: ${{ github.sha }}
      short: ${{ contains(github.event.pull_request.labels.*.name, 'ci-short') }}
