name: on-pull-request-comment

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  cd:
    if: ${{ contains(github.event.comment.body, '/e2e') }}
    uses: ./.github/workflows/_sls_deploy.yml
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: false
  
  e2e:
    if: ${{ contains(github.event.comment.body, '/e2e') }}
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: false
