name: on-schedule-e2e

on:
  schedule:
    - cron: '30 15 * * *'

jobs:
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: main
      notify: true
      stage: ${{ matrix.stage }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    strategy:
      fail-fast: false
      matrix:
        stage:
          - stg
          # - prd
