name: on-schedule-e2e

on:
  schedule:
    - cron: '30 15 * * *'

jobs:
  e2e-mobile:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: main
      notify: true
      stage: ${{ matrix.stage }}
      viewport: mobile
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
      SHOPIFY_ADMIN_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_ACCESS_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        stage:
          - prd
  e2e-desktop:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: e2e-mobile
    with:
      ref: main
      notify: true
      stage: ${{ matrix.stage }}
      viewport: desktop
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
      SHOPIFY_ADMIN_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_ACCESS_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        stage:
          - prd