name: on-schedule-e2e

on:
  schedule:
    - cron: '30 15 * * *'

jobs:
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: main
      notify: true
      stage: ${{ matrix.stage }}
      groups: "[1,2,3,4,5,6,7,8,9,10]"
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        stage:
          - dev
          - stg
          - prd