name: run-e2e

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Stage to run tests against
        options:
        - all
        - dev
        - stg
      browser:
        type: choice
        description: Browser to run tests on
        options:
        - chromium   # chrome
        - webkit     # safari
        - firefox
      load:
        type: boolean
        description: Enable load multiplier
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      stages: ${{ steps.set-matrix.outputs.stages }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ inputs.stage }}" = "all" ]; then
            echo stages='["dev","stg"]' >> $GITHUB_OUTPUT
          else
            echo stages='["${{ inputs.stage }}"]' >> $GITHUB_OUTPUT
          fi

  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: setup
    with:
      ref: ${{ github.ref_name }}
      stage: ${{ matrix.stage }}
      browser: ${{ inputs.browser }}
      load: ${{ inputs.load && 10 || 1 }}
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        stage: ${{fromJson(needs.setup.outputs.stages)}}
