name: run-release-stg

on:
  workflow_dispatch:
    inputs:
      semver:
        type: string
        description: semver
        required: true

jobs:
  validate-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate semver
        run: |
          if [[ ! ${{ inputs.semver }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid semver: ${{ inputs.semver }}"
            exit 1
          fi

  ci:
    uses: ./.github/workflows/_unit_tests.yml
    with:
      ref: ${{ github.ref_name }}

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    with:
      ref: ${{ github.ref_name }}
      stage: stg
      notify: true
  
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: ${{ github.ref_name }}
      stage: stg
      notify: true