name: run-release-stg

on:
  workflow_dispatch:
    inputs:
      semver:
        type: string
        description: semver
        required: true

concurrency:
  group: ${{ github.workflow }}-stg
  cancel-in-progress: false

jobs:
  validate-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate semver
        run: |
          if [[ ! ${{ inputs.semver }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid semver: ${{ inputs.semver }}"
            exit 1
          fi

  ci:
    uses: ./.github/workflows/_unit_tests.yml
    needs: validate-semver
    with:
      ref: ${{ github.sha }}

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    needs: ci 
    with:
      ref: ${{ github.sha }}
      stage: dev
      notify: true
      release_semver: ${{ inputs.semver }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}