name: run-e2e

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Stage to run tests against
        options:
        - dev
        - stg
        - prd
      viewport:
        type: choice
        description: Device to run tests on
        options:
        - mobile
        - desktop
        - all
      browser:
        type: choice
        description: Browser to run tests on
        options:
        - chromium   # chrome
        - webkit     # safari
        - firefox

jobs:
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    environment: ${{ inputs.stage }}
    with:
      ref: ${{ github.ref_name }}
      stage: ${{ inputs.stage }}
      browser: ${{ inputs.browser }}
      notify: true
      viewport: ${{ inputs.viewport }}
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
      SHOPIFY_ADMIN_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_ACCESS_TOKEN }}
