name: run-breakglass-deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Stage to deploy to
        options:
        - dev
        - stg
        - prd

concurrency:
  group: ${{ github.workflow }}-${{ inputs.stage }}
  cancel-in-progress: false

jobs:
  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    with:
      ref: ${{ github.sha }}
      stage: ${{ inputs.stage }}
      url: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
      notify: false
  
  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: ${{ inputs.stage }}
      notify: false
    secrets:
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
