name: run-release-stg

on:
  workflow_dispatch:
    inputs:
      cfn_deploy:
        type: boolean
        description: Deploy via CloudFormation
        default: false
      semver:
        type: string
        description: semver
        required: true

concurrency:
  group: ${{ github.workflow }}-stg
  cancel-in-progress: false

jobs:
  validate-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate semver
        run: |
          if [[ ! ${{ inputs.semver }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid semver: ${{ inputs.semver }}"
            exit 1
          fi
      
      - name: Ensure tag does not exist
        run: |
          release=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.semver }})
          if [[ $release_code == "200" ]]; then
            echo "Tag ${{ inputs.semver }} already exists."
            exit 1
          fi

  ci:
    uses: ./.github/workflows/_unit_tests.yml
    needs: validate-semver
    with:
      ref: ${{ github.sha }}

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    needs: ci 
    with:
      ref: ${{ github.sha }}
      release_semver: ${{ inputs.semver }}
      stage: dev
      notify: true
      cfn_deploy: ${{ inputs.cfn_deploy }}
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  e2e:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ github.ref_name }}
      stage: dev
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}