name: run-release-prd
run-name: ${{ inputs.semver }}

on:
  workflow_dispatch:
    inputs:
      semver:
        type: string
        description: semver
        required: true

concurrency:
  group: ${{ github.workflow }}-prd
  cancel-in-progress: false

jobs:
  validate-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      statuses: read
    steps:
      - name: Validate semver
        run: |
          if [[ ! ${{ inputs.semver }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid semver: ${{ inputs.semver }}"
            exit 1
          fi

      - name: Verify GitHub release E2E status
        id: get-release-hash
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "${{ inputs.semver }}"
            });
            if (!release) {
              core.setFailed(`Release ${{ inputs.semver }} does not exist.`);
            }
            console.log(`Release SHA: ${release.data.target_commitish}`);

            const statuses = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${release.data.target_commitish}`
            });
            console.log(`Commit statuses: ${JSON.stringify(statuses.data)}`);

            const e2e = statuses.data.find(status => status.context === 'run-release-stg / e2e');
            if (e2e.state != 'success') {
              core.setFailed(`Release ${{ inputs.semver }} e2e status is ${e2e.state}`);
            }

  cd:
    uses: ./.github/workflows/_sls_deploy.yml
    needs: validate-release
    with:
      ref: ${{ github.sha }}
      stage: prd
      url: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.semver }}
      notify: true
      release_semver: ${{ inputs.semver }}
      release_reuse: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  e2e-tests:
    uses: ./.github/workflows/_e2e_tests.yml
    needs: cd
    with:
      ref: ${{ inputs.semver }}
      stage: prd
      notify: true
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      X_API_ACCESS_TOKEN: ${{ secrets.X_API_ACCESS_TOKEN }}
      SHOPIFY_ADMIN_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_ACCESS_TOKEN }}