name: scheduled-e2e

on:
  schedule:
    - cron: '0 8,12,16,20 * * *'

jobs:
  test:
    uses: ./.github/workflows/_e2e_tests.yml
    with:
      ref: main
      stage: ${{ matrix.stage }}
    strategy:
      fail-fast: false
      matrix:
        stage:
          - dev
          - stg
